def jknjob_versions = [release:"", rcp: '0.0.0.snapshot', rtlib:'0.0.0.snapshot']

pipeline {
    agent none

    environment {
        JKNBUILD_DIST = 'JKNS_DIST'
    }


    options {
        timeout(time: 30, unit: 'MINUTES')
    }


    stages {
        stage("Building Source Code") {
            agent {
                label 'Node.Build'
            }

            stages {
                stage('Versioning') {
                    steps {
                        script {
                            def versioning_method = load("Example-LoadGroovyScript/scripts/versions.groovy")
                            versioning_method.doA()
                            echo(versioning_method.doB("88"))
                            jknjob_versions = versioning_method.doVersion(readProperties(file: 'Example-LoadGroovyScript/VERSIONS'))
                        }
                    }
                }

               stage("build") {
                    steps {
                        withEnv(["BLD_VERSION=${jknjob_versions.RCP}", "MK_OUTPUTDIR=${env.JKNBUILD_DIST}"
                                ]) {
                            sh "make -C Example-LoadGroovyScript build"
                        }
                    }
               }

               stage("test") {
                   steps {
                       sh "./test.sh"
                   }
               }
            }
        }
    }
}


// pipeline {
//     agent any



//     stages {

//         stage('Building Source Code') {
//             stages {
//                 agent { label 'Node.Build' }

//                 stage('Versioning') {
//                     script {
//                         def versioning_method = load("Example-LoadGroovyScript/scripts/versions.groovy")
//                         jknjob_versions = versioning_method("1", readProperties(file: 'VERSION'))
//                     }
//                 }


//                 stage('Compiling') {
//                     withEnv(["BLD_VERSION=${jknjob_versions.RCP}", "MK_OUTPUTDIR=${env.JKNBUILD_DIST}"
//                             ]) {
//                         sh "make build"
//                     }
//                 }
//             }
//         }


//         // stage('Automated Test') {
//         //     stages {
//         //         agent { label 'Node.Test' }

//         //         stage('Executing') {
//         //             sh "make test"
//         //         }
//         //     }
//         // }
//     }
// }
