
build:
	echo "Building ..."
	echo "BLD_VERSION=$(BLD_VERSION)"
	echo "MK_OUTPUTDIR=$(MK_OUTPUTDIR)"
	echo "Done building"


Test:
	echo "Building ..."
	echo "BLD_VERSION=$(BLD_VERSION)"
	echo "MK_OUTPUTDIR=$(MK_OUTPUTDIR)"
	echo "Done building"